# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=22, verbose_name='活动名字')),
                ('activity_photo', models.ImageField(blank=True, max_length=500, null=True, upload_to='activity', verbose_name='活动图片地址')),
                ('activity_address', models.CharField(max_length=50, verbose_name='活动链接地址')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=22, verbose_name='专区名字')),
                ('region_introduce', models.CharField(max_length=50, verbose_name='专区描述')),
                ('region_order', models.IntegerField(verbose_name='专区排序')),
                ('region_show', models.IntegerField(choices=[(1, '上架'), (2, '下架')], default=1, verbose_name='上架状态')),
                ('region_add_time', models.DateTimeField(auto_now_add=True, verbose_name='专区添加时间')),
                ('region_edit_time', models.DateTimeField(auto_now=True, verbose_name='专区修改时间')),
                ('region_status', models.BooleanField(default=False, verbose_name='专区删除状态')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityRegionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ARP_add_time', models.DateTimeField(auto_now_add=True, verbose_name='专区活动商品添加时间')),
                ('ARP_edit_time', models.DateTimeField(auto_now=True, verbose_name='专区活动商品修改时间')),
                ('ARP_status', models.BooleanField(default=False, verbose_name='专区活动商品删除状态')),
                ('ARP_region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ActivityRegion', verbose_name='活动专区id')),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_name', models.CharField(max_length=32, verbose_name='轮播图名字')),
                ('carousel_url', models.ImageField(blank=True, max_length=500, null=True, upload_to='carousel', verbose_name='轮播图片地址')),
                ('carousel_order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('carousel_add_time', models.DateTimeField(auto_now_add=True, verbose_name='轮播添加时间')),
                ('carousel_edit_time', models.DateTimeField(auto_now=True, verbose_name='轮播修改时间')),
                ('carousel_status', models.BooleanField(default=False, verbose_name='轮播删除状态')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.ImageField(blank=True, max_length=500, null=True, upload_to='photo', verbose_name='图片地址')),
                ('photo_add_time', models.DateTimeField(auto_now_add=True, verbose_name='图片添加时间')),
                ('photo_edit_time', models.DateTimeField(auto_now=True, verbose_name='图片修改时间')),
                ('photo_status', models.BooleanField(default=False, verbose_name='图片删除状态')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(default='个', max_length=10, verbose_name='单位添加时间')),
                ('unit_add_time', models.DateTimeField(auto_now_add=True, verbose_name='单位添加时间')),
                ('unit_edit_time', models.DateTimeField(auto_now=True, verbose_name='单位修改时间')),
                ('unit_status', models.BooleanField(default=False, verbose_name='单位删除状态')),
            ],
        ),
        migrations.CreateModel(
            name='ProCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=32, verbose_name='分类名')),
                ('category_introduce', models.CharField(blank=True, max_length=50, null=True, verbose_name='分类简介')),
                ('category_add_time', models.DateTimeField(auto_now_add=True, verbose_name='分类添加时间')),
                ('category_edit_time', models.DateTimeField(auto_now=True, verbose_name='分类修改时间')),
                ('category_status', models.BooleanField(default=False, verbose_name='删除状态')),
            ],
        ),
        migrations.CreateModel(
            name='ProSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=32, verbose_name='商品名')),
                ('pro_introduce', models.CharField(blank=True, max_length=50, null=True, verbose_name='商品简介')),
                ('pro_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='商品价格')),
                ('pro_unit', models.CharField(default='个', max_length=10, verbose_name='商品单位')),
                ('pro_inventory', models.IntegerField(default=0, verbose_name='商品库存')),
                ('pro_sales_volume', models.IntegerField(blank=True, null=True, verbose_name='商品销量')),
                ('pro_logo', models.ImageField(blank=True, max_length=500, null=True, upload_to='pro', verbose_name='商品LOGO地址')),
                ('pro_show', models.IntegerField(choices=[(1, '上架'), (2, '下架')], default=1, verbose_name='上架状态')),
                ('pro_add_time', models.DateTimeField(auto_now_add=True, verbose_name='商品添加时间')),
                ('pro_edit_time', models.DateTimeField(auto_now=True, verbose_name='商品修改时间')),
                ('pro_status', models.BooleanField(default=False, verbose_name='商品删除状态')),
                ('pro_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProCategory', verbose_name='商品分类id')),
            ],
        ),
        migrations.CreateModel(
            name='ProSPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spu_name', models.CharField(max_length=32, verbose_name='商品spu名')),
                ('spu_introduce', models.CharField(blank=True, max_length=50, null=True, verbose_name='商品spu详情')),
                ('spu_add_time', models.DateTimeField(auto_now_add=True, verbose_name='商品spu添加时间')),
                ('spu_edit_time', models.DateTimeField(auto_now=True, verbose_name='商品spu修改时间')),
                ('spu_status', models.BooleanField(default=False, verbose_name='商品spu删除状态')),
            ],
        ),
        migrations.AddField(
            model_name='prosku',
            name='pro_spu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProSPU', verbose_name='商品spuid'),
        ),
        migrations.AddField(
            model_name='photoalbum',
            name='photo_sku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProSKU', verbose_name='图片sku_id'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='carousel_sku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProSKU', verbose_name='轮播sku_id'),
        ),
        migrations.AddField(
            model_name='activityregionproduct',
            name='ARP_sku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProSKU', verbose_name='专区活动商品sku_id'),
        ),
    ]
