# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': '活动管理', 'verbose_name_plural': '活动管理'},
        ),
        migrations.AlterModelOptions(
            name='activityregion',
            options={'verbose_name': '活动专区管理', 'verbose_name_plural': '活动专区管理'},
        ),
        migrations.AlterModelOptions(
            name='activityregionproduct',
            options={'verbose_name': '专区活动商品管理', 'verbose_name_plural': '专区活动商品管理'},
        ),
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': '轮播图管理', 'verbose_name_plural': '轮播图管理'},
        ),
        migrations.AlterModelOptions(
            name='photoalbum',
            options={'verbose_name': '商品相册管理', 'verbose_name_plural': '商品相册管理'},
        ),
        migrations.AlterModelOptions(
            name='photounit',
            options={'verbose_name': '商品单位管理', 'verbose_name_plural': '商品单位管理'},
        ),
        migrations.AlterModelOptions(
            name='procategory',
            options={'verbose_name': '分类管理', 'verbose_name_plural': '分类管理'},
        ),
        migrations.AlterModelOptions(
            name='prosku',
            options={'verbose_name': '商品管理', 'verbose_name_plural': '商品管理'},
        ),
        migrations.AlterModelOptions(
            name='prospu',
            options={'verbose_name': '商品SPU', 'verbose_name_plural': '商品SPU'},
        ),
    ]
