# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_auto_20181119_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(max_length=32, null=True, verbose_name='用户名'),
        ),
    ]
