# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0003_auto_20181119_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='删除状态'),
        ),
        migrations.AddField(
            model_name='users',
            name='user_head',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='user/%Y%m/%d', verbose_name='头像'),
        ),
    ]
