# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0004_auto_20181120_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_head',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='user', verbose_name='头像'),
        ),
    ]
